add_newline = true

format = """
$username$hostname$directory$git_branch$git_status
$character"""

[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
style = "bold green"
format = "[@$hostname]($style) "

[directory]
style = "bold cyan"
format = "in [$path]($style) "
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "git:"
style = "bold yellow"
format = "[$symbol($branch)]($style) "

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style)"
conflicted = "="
ahead = "↑${count}"
behind = "↓${count}"
diverged = "↕↑${ahead_count}↓${behind_count}"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = ">"
deleted = "x"

[character]
success_symbol = "[>](bold green) "
error_symbol = "[>](bold red) "
vimcmd_symbol = "[>](bold blue) "
